server:
  port: 5601

spring:
  application:
    name: job-portal
  datasource:
    url: jdbc:postgresql://localhost:5432/job_portal
    username: shreyasjakati
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger
